//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labitec.LeadForce.API.Client.ContactClientReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContactClientReference.IContact")]
    public interface IContact {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContact/GetContacts", ReplyAction="http://tempuri.org/IContact/GetContactsResponse")]
        string GetContacts(System.Guid siteId, string username, string password, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContact/UpdateContact", ReplyAction="http://tempuri.org/IContact/UpdateContactResponse")]
        string UpdateContact(System.Guid siteId, string username, string password, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContact/CheckName", ReplyAction="http://tempuri.org/IContact/CheckNameResponse")]
        string CheckName(System.Guid siteId, string username, string password, string fullName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContactChannel : Labitec.LeadForce.API.Client.ContactClientReference.IContact, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactClient : System.ServiceModel.ClientBase<Labitec.LeadForce.API.Client.ContactClientReference.IContact>, Labitec.LeadForce.API.Client.ContactClientReference.IContact {
        
        public ContactClient() {
        }
        
        public ContactClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetContacts(System.Guid siteId, string username, string password, string xml) {
            return base.Channel.GetContacts(siteId, username, password, xml);
        }
        
        public string UpdateContact(System.Guid siteId, string username, string password, string xml) {
            return base.Channel.UpdateContact(siteId, username, password, xml);
        }
        
        public string CheckName(System.Guid siteId, string username, string password, string fullName) {
            return base.Channel.CheckName(siteId, username, password, fullName);
        }
    }
}
