//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labitec.LeadForce.API.Client.RequirementClientReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RequirementClientReference.IRequirement")]
    public interface IRequirement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequirement/GetRequirements", ReplyAction="http://tempuri.org/IRequirement/GetRequirementsResponse")]
        string GetRequirements(System.Guid siteId, string username, string password, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequirement/UpdateRequirement", ReplyAction="http://tempuri.org/IRequirement/UpdateRequirementResponse")]
        string UpdateRequirement(System.Guid siteId, string username, string password, string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequirementChannel : Labitec.LeadForce.API.Client.RequirementClientReference.IRequirement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequirementClient : System.ServiceModel.ClientBase<Labitec.LeadForce.API.Client.RequirementClientReference.IRequirement>, Labitec.LeadForce.API.Client.RequirementClientReference.IRequirement {
        
        public RequirementClient() {
        }
        
        public RequirementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequirementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequirementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequirementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRequirements(System.Guid siteId, string username, string password, string xml) {
            return base.Channel.GetRequirements(siteId, username, password, xml);
        }
        
        public string UpdateRequirement(System.Guid siteId, string username, string password, string xml) {
            return base.Channel.UpdateRequirement(siteId, username, password, xml);
        }
    }
}
