//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labitec.LeadForce.Portal.Main.TaskModule {
    
    
    public partial class Tasks {
        
        /// <summary>
        /// RadScriptBlock1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadScriptBlock RadScriptBlock1;
        
        /// <summary>
        /// RadPanelBar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadPanelBar RadPanelBar1;
        
        /// <summary>
        /// tagsTasks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.UI.BaseWorkspace.Tags tagsTasks;
        
        /// <summary>
        /// filtersTasks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.UI.BaseWorkspace.Filters filtersTasks;
        
        /// <summary>
        /// ucTaskFilter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.LeadForce.Portal.Main.TaskModule.UserControls.TaskFilter ucTaskFilter;
        
        /// <summary>
        /// gridTasks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.UI.BaseWorkspace.Grid gridTasks;
        
        /// <summary>
        /// GridColumn1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.UI.BaseWorkspace.GridColumn GridColumn1;
        
        /// <summary>
        /// GridColumn2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.UI.BaseWorkspace.GridColumn GridColumn2;
        
        /// <summary>
        /// GridColumn3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.UI.BaseWorkspace.GridColumn GridColumn3;
        
        /// <summary>
        /// GridColumn4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.UI.BaseWorkspace.GridColumn GridColumn4;
        
        /// <summary>
        /// GridColumn5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.UI.BaseWorkspace.GridColumn GridColumn5;
        
        /// <summary>
        /// GridColumn6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.UI.BaseWorkspace.GridColumn GridColumn6;
        
        /// <summary>
        /// GridColumn8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.UI.BaseWorkspace.GridColumn GridColumn8;
        
        /// <summary>
        /// GridColumn7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.UI.BaseWorkspace.GridColumn GridColumn7;
        
        /// <summary>
        /// GridJoin1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.UI.BaseWorkspace.GridJoin GridJoin1;
        
        /// <summary>
        /// GridJoin2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.UI.BaseWorkspace.GridJoin GridJoin2;
        
        /// <summary>
        /// GridJoin3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.UI.BaseWorkspace.GridJoin GridJoin3;
        
        /// <summary>
        /// rScheduler control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadScheduler rScheduler;
    }
}
