//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labitec.LeadForce.Portal.Main.Discussions {
    
    
    public partial class Discussion {
        
        /// <summary>
        /// ucPublicationTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.LeadForce.Portal.Main.Discussions.UserControls.ActivityRibbon.PublicationTypes ucPublicationTypes;
        
        /// <summary>
        /// ucPublicationCategory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.LeadForce.Portal.Main.Discussions.UserControls.ActivityRibbon.PublicationCategory ucPublicationCategory;
        
        /// <summary>
        /// plArticle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel plArticle;
        
        /// <summary>
        /// lrlTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lrlTitle;
        
        /// <summary>
        /// plImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel plImage;
        
        /// <summary>
        /// rbiImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadBinaryImage rbiImage;
        
        /// <summary>
        /// lrlText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lrlText;
        
        /// <summary>
        /// plOffComment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel plOffComment;
        
        /// <summary>
        /// lrlOffComment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lrlOffComment;
        
        /// <summary>
        /// ucPublicationComment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.LeadForce.Portal.Shared.UserControls.PublicationComment ucPublicationComment;
        
        /// <summary>
        /// ucNotificationMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Labitec.LeadForce.Portal.Shared.UserControls.NotificationMessage ucNotificationMessage;
    }
}
